use serde::Deserialize;

#[derive(Debug, Deserialize, Clone, Default)]
pub struct ServerConfigFile {
    pub control_addr: Option<String>,
    pub api_addr: Option<String>,
    pub admin_password: Option<String>,
    pub jwt_secret: Option<String>,
    pub client_auth_token: Option<String>,
    pub tls: Option<bool>,
    pub tls_cert: Option<String>,
    pub tls_key: Option<String>,
    pub log: Option<String>,
    pub db_path: Option<String>,
    pub ss_enabled: Option<bool>,
    pub ss_port: Option<u16>,
    pub ss_cipher: Option<String>,
    pub ss_password: Option<String>,
    pub trojan_enabled: Option<bool>,
    pub trojan_port: Option<u16>,
    pub trojan_password: Option<String>,
    pub trojan_fallback: Option<String>,
    pub dns_enabled: Option<bool>,
    pub dns_bind: Option<String>,
    pub dns_tunnel_domain: Option<String>,
    pub dns_mesh_domain: Option<String>,
    pub reverse_proxy_enabled: Option<bool>,
    pub reverse_proxy_max_connections: Option<u32>,
    pub reverse_proxy_connection_timeout: Option<u64>,
    pub reverse_proxy_buffer_size: Option<usize>,
    pub api_tls: Option<bool>,
    pub api_domain: Option<String>,
    pub acme_enabled: Option<bool>,
    pub acme_server_url: Option<String>,
    pub acme_cert_dir: Option<String>,
    pub acme_auto_renew: Option<bool>,
    pub acme_renewal_check_interval: Option<u64>,
    pub acme_renewal_days_before_expiry: Option<u64>,
    pub acme_email: Option<String>,
    pub acme_tos_agreed: Option<bool>,
}
