[package]
name = "rust-tunnel-common"
version = "0.4.0"
edition = "2021"
description = "Shared protocol and infrastructure for rust-tunnel"
license = "MIT"

[lints]
workspace = true

[dependencies]
aes-gcm.workspace = true
base64.workspace = true
bincode.workspace = true
rand.workspace = true
rcgen.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
